python scripts/train_score.py \
  --data "$PREPROC_DIR" \
  --preprocessed \
  --output "$SCORE_CKPT" \
  --channels 1 \
  --spatial-dims 3 \
  --include "*.pt" \
  --epochs 100 \
  --batch-size 4 \
  --base-channels 32 \
  --depth 3 \
  --device cuda \
  --val-fraction 0.05 \
  --augment \
  --log-every 100